### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by igor-v-nikolaev** [ANAVADH/ITEM_CUD#1]
I'm trying to access any pages but is always forwarded to login page (http://localhost:3000/login).
Could you please fix this behaviour.

**Comment by ANAVADH** [comment]
Currently all other pages are protected 

- Dashboard page (user login)
- Admin page (Admin login )

**Comment by igor-v-nikolaev** [comment]
But in requirements we have that anybody can see items. You need to login only to create a new item or delete your item.
Please implement this.

**Comment by ANAVADH** [comment]
I have create a view all items page at '/items'

- At the login page i have added a button to view items.
- Anybody can view the item gallery.
- Now the login user is only allowed to view and delete the item that they have created.
