### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by igor-v-nikolaev** [ANAVADH/ITEM_CUD#2]
How can I register a new user?

**Comment by ANAVADH** [comment]
- Currently the 1st user must be added manually to db  note (store password after bycrypt)

- user with ID 1 is considered as Admin
- you can signin admin and add other user then login. 

- if you want I will make a interface for creating admin

**Comment by igor-v-nikolaev** [comment]
Yes, please add a registration page.

**Comment by ANAVADH** [comment]
Yes , Now I have added a create admin page at  "/" 

Note: Only one admin  can be created; also, that must be the first user
- if there are other user in the users table, the create admin page will not show up and will be redirected to "/login"

-  after creating admin, you can login to admin panel from login page and add users from admin panel. 

After successfully adding users, you can login to that user's account via the login page using their email and password.
