### ISSUE TITLE
Anybody Can See All Items

### ISSUE THREAD

**Issue by igor-v-nikolaev** [ANAVADH/ITEM_CUD#3]
Requirement is not implemented:
Anybody, even without login, can see all items.
Please implement this requirement.
Thank you, Igor

**Comment by ANAVADH** [comment]
![img](https://github.com/user-attachments/assets/3d4913b5-6254-488c-b200-1097d85c1d82)

**Comment by ANAVADH** [comment]
- Currently, even without a login, anybody can view Items.(Refer previous comment - image)
- But initially, an admin must be registered.
- Logically, without an admin, there is no need to show admin login or user login page in our case '/login'

**Comment by ANAVADH** [comment]
![img 2](https://github.com/user-attachments/assets/edd13689-8105-454b-b913-058c5d5f15d3)

- If you want, I will add the view item button here. but I think that will not be logically correct.
- If there is no admin, there will be no user, hence there will be zero items.
